#ifndef DISCRETE_MATHEMATICS_CHAPTER_3_COMPLEXITY_OF_ALGORITHMS_ALL_HEADERS_H_
#define DISCRETE_MATHEMATICS_CHAPTER_3_COMPLEXITY_OF_ALGORITHMS_ALL_HEADERS_H_

#include "solution_1.h"
#include "solution_2.h"
#include "solution_3.h"
#include "solution_4.h"
#include "solution_5.h"
#include "solution_6.h"
#include "solution_7.h"
#include "solution_8.h"
#include "solution_9.h"
#include "solution_10.h"
#include "solution_11.h"
#include "solution_12.h"
#include "solution_13.h"
#include "solution_14.h"
#include "solution_15.h"
#include "solution_16.h"
#include "solution_17.h"
#include "solution_25.h"
#include "solution_26.h"
#include "solution_27.h"
#include "solution_28.h"
#include "solution_29.h"
#include "solution_30.h"
#include "solution_31.h"
#include "solution_32.h"
#include "solution_33.h"
#include "solution_34.h"
#include "solution_35.h"
#include "solution_36.h"
#include "solution_42.h"
#include "solution_46.h"

#endif // DISCRETE_MATHEMATICS_CHAPTER_3_COMPLEXITY_OF_ALGORITHMS_ALL_HEADERS_H_
